version: "3.5"
   
services:
  db:
    image: postgres
    container_name: postgres_container
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file: 
      - ./center/.env.db
    restart: unless-stopped
    networks: 
      iotanalyzer:
    
  web:
    build: .
    container_name: center_server_1
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - ./center:/center
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: always
    networks:
      iotanalyzer:

networks: 
  iotanalyzer:
    driver: bridge


